### ISSUE TITLE
Auto-Join issues with Kubernetes

### ISSUE THREAD

**Issue by rclayton-the-terrible** [distribworks/dkron-helm#1]
When using the Helm chart, we cannot specify more than 3 `server.replicas` for server nodes or the cluster will not bootstrap (I've tried multiple times).

The workaround is to install the cluster:

```bash
helm install --name dkron ./dkron-helm
```

When the cluster is formed, bring up additional server nodes one at a time:

```bash
kubectl scale deployment dkron-server --replicas=4
# Watch logs to make sure they come online
kubectl scale deployment dkron-server --replicas=5
# Watch again.
```

**Comment by victorcoder** [comment]
Fixed in #3
