### ISSUE TITLE
Issues with helm repo add

### ISSUE THREAD

**Issue by axoxymous-coder** [distribworks/dkron-helm#5]
Hi Team,

I was trying to use the _dkron_ helm chart to install in my local k8s cluster. However I am encountering the following error while trying to add the repo:

```
helm repo add dkron https://github.com/distribworks/dkron-helm/dkron
Error: looks like "https://github.com/distribworks/dkron-helm/dkron" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/distribworks/dkron-helm/dkron/index.yaml : 404 Not Found
```

Can someone please help how do I use the _dkron-helm_ to install _dkron_ in my K8s cluster?

Thanks.

**Comment by vcastellm** [comment]
This won't work without the package in the repository AFAIK

I just packaged and pushed it to the repo.

You can install like: `helm repo add dkron https://raw.githubusercontent.com/distribworks/dkron-helm/master`
